### ISSUE TITLE
z_init_logger is not found in zenoh-c

### ISSUE THREAD

**Issue by comoc** [eclipse-zenoh/zenoh-csharp#3]
Hi, I am reporting a problem in Zenoh.cs.

Zenoh.cs is trying to import z_init_logger [here](https://github.com/eclipse-zenoh/zenoh-csharp/blob/278f6733b488fcbd6f694a9b734be6bf5de378c1/Zenoh/Zenoh.cs#L24), but zenoh-c does not implement this function.
Please see [here](https://github.com/search?q=repo%3Aeclipse-zenoh%2Fzenoh-c%20z_init_logger&type=code)

Other functions such as `zn_config_from_str` and `zn_open` were also not found.

**Comment by knutur94** [comment]
I think the problem is that this repo is compatible with earlier versions of zenoh-c ( version 0.7 or something), which doesn't work with version 1.0.x. According to the discord server, there isn't any plans of updating this repo at his stage either.

**Comment by comoc** [comment]
I understand. Thank you for the information.

**Comment by knuttu94** [comment]
FYI, a working version an be found here: https://github.com/sanri/zenoh-csharp/tree/master
